config/routes.rb
BlogTest::Application.routes.draw do
  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :commentor, :presence => true 
  validates :body, :presence => true 
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, :presence => true 
  validates :text, :presence => true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @post=Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update(post_params)
      redirect_to post_path(@post)
    else
      render action: 'edit'
    end
  end
  

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(post_params)
    @post.comments << @comment
    if @comment.save
      redirect_to post_path(@post) #, notice: 'Course was successfully created.' 
    else
      render action: 'new' 
    end
  end

  def destroy
  end
  
  def post_params
    params.require(:comment).permit(:commentor, :body)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def edit
    @post = Post.find(params[:id])
  end
    
  def update
    @post=Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render action: 'edit'
    end
  end
    
    

  
  def create

    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path #, notice: 'Course was successfully created.' 
    else
      render action: 'new' 
    end

  end
    
    
  def post_params
    params.require(:post).permit(:title, :text)
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for [@post,@comment] do |f|%>

	<%= f.label :commentor %><br>
	<%= f.text_field :commentor %><br><br>

	<%= f.label :body %><br>
	<%= f.text_area :body %><br><br>

    <%= f.submit %>

<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<%=render 'form'%>

app/views/comments/new.html.erb
<%=render 'form'%>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogTest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f|%>

	<%= f.label :title %><br>
	<%= f.text_field :title %><br><br>

	<%= f.label :text %><br>
	<%= f.text_area :text %><br><br>

    <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Posts</h1>


<% @posts.each do |post| %>
	title: <%= post.title %><br \>
	Text: <%= post.text %><br \>
	<%= link_to 'Show', post %> | <%= link_to 'Edit', edit_post_path(post) %> 
	
<% end %>


<br \><br \>
<%= link_to 'New Post', new_post_path %>

<br \><br \>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<h1>Post:</h1>

title: <%= @post.title %> 
<br \>
Text: <%= @post.text %> 


<br \>

<h1>Comments:</h1>

<% @post.comments.each do |comment| %>

Commentor: <%= comment.commentor %><br>
Body: <%= comment.body %><br>
<%=link_to 'Edit', edit_post_comment_path(@post,comment)%>
<br><br>
<% end %>

<%=link_to 'New Comment', new_post_comment_path(@post)%>